# Fly.io Configuration for PayLens Backend
app = "paylens-backend"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    force_https = true

[env]
  NODE_ENV = "production"

# Mount a volume for persistent data (if needed)
# [[mounts]]
#   source = "paylens_data"
#   destination = "/data"

# Database configuration will be set via environment variables
